version: "3.7"
services:
  app:
    container_name: chatApp_production
    restart: "no"
    build:
      context: .
      args:
        env: 'production'
    image: chatapp:production
    ports:
      - "3000:3000"
    links:
      - mongo

    networks:
      - app-network
  mongo:
    container_name: mongo
    image: mongo:4.0
    ports:
      - "27018:27017"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


