version: "3.7"
services:
  app:
    container_name: chat_mainservice
    restart: "no"
    build:
      context: .
      args:
        env: 'dev'
    image: node.chat:dev
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
    networks:
      - app-network
  mongo:
    container_name: mongo
    image: mongo:4.0
    ports:
      - "27018:27017"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


